name: Integration-EntraID

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - main
      - '[0-9].*'
  pull_request:
    branches:
      - main
      - '[0-9].*'
  schedule:
    - cron: '0 1 * * *' # nightly build
  workflow_dispatch:

jobs:

  build:
    name: Build and Test EntraID
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./entraid
    steps:
      - uses: actions/checkout@v2
          
      - name: Set up publishing to maven central
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: entraid-${{hashFiles('**/pom.xml')}}

      - name: Maven offline-core
        run: |
          mvn -q dependency:go-offline
        working-directory: ./core
      - name: Build and install Core into local repo
        run: |
          mvn clean install -DskipTests  # Skip tests for faster builds, but you can remove the flag if needed
        working-directory: ./core

      - name: Build docs
        run: |
          mvn javadoc:jar
      - name: Build with Maven
        run: mvn compile
      - name: Test with Maven
        run: mvn test
        env:
          AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          AZURE_AUTHORITY: ${{secrets.AZURE_AUTHORITY}}
          AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
          AZURE_CERT: ${{secrets.AZURE_CERT}}
          AZURE_PRIVATE_KEY: ${{secrets.AZURE_PRIVATE_KEY}}
          AZURE_REDIS_SCOPES: ${{secrets.AZURE_REDIS_SCOPES}}
