---

  name: Publish Snapshot-EntraID
  
  on:
    push:
      branches:
        - main
        - '[0-9].x'
    workflow_dispatch:
  
  jobs:
  
    snapshot:
      name: Deploy Snapshot-EntraID
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./entraid
      steps:
        - uses: actions/checkout@v2
        
        - name: Set up publishing to maven central
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'temurin'
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_PASSWORD
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: |
              ~/.m2/repository
              /var/cache/apt
            key: entraid-${{hashFiles('**/pom.xml')}}

        - name: Maven offline-core
          run: |
            mvn -q dependency:go-offline
          working-directory: ./core
        - name: Build and install Core into local repo
          run: |
            mvn clean install -DskipTests  # Skip tests for faster builds, but you can remove the flag if needed
          working-directory: ./core
                      
        - name: Maven offline
          run: |
            mvn -q dependency:go-offline
        - name: deploy
          run: |
            mvn --no-transfer-progress \
              -DskipTests  -Dmaven.test.skip=true deploy
          env:
            MAVEN_USERNAME: ${{secrets.OSSH_USERNAME}}
            MAVEN_PASSWORD: ${{secrets.OSSH_TOKEN}}
